In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30])
arr

array([10, 20, 30])

In [3]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array([10, 3.14, 'abc', True])
arr1

array(['10', '3.14', 'abc', 'True'], dtype='<U32')

In [11]:
arr

array([10, 20, 30])

In [12]:
arr.shape

(3,)

In [14]:
arr.ndim

1

In [13]:
arr.size

3

In [21]:
arr2 = np.array([[10,20,30,40], [50,60,70,80], [90,100,100,120]])
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 100, 120]])

In [24]:
arr2[0,1], arr2[1,3], arr2[2,2]

(20, 80, 100)

In [ ]:
arr3 = np.arange(1,25).reshape((2,4,3))     #2 elements of 4 rows and 3 columns
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [35]:
arr3[0,2,0], arr3[1,1,2], arr3[1,3,1], arr3[0,3,1]

(7, 18, 23, 11)

In [40]:
#10, 5, 21, 22

arr3[0,3,0],arr3[0,1,1], arr3[1,2,2], arr3[1,3,0]

(10, 5, 21, 22)

In [44]:
arr4 = np.arange(1,31).reshape((6,5))
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr4[1:5]   # start to end-1  = [1,4]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr4[2:4]       #[2,3] rows

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
arr4[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr4[:, 1]          #all row and 1st column

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
arr4[:, 1:4]            #all row and 1 to 3rd column

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [54]:
arr4[:, 1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25],
       [27, 28, 29, 30]])

In [58]:
arr4[1:5, 1:4]          #arr[row, column]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])