In [1]:
import numpy as np

In [6]:
arr1 = np.arange(1, 10).reshape((3,3))
arr2 = np.arange(2, 11).reshape((3,3))

arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]))

In [7]:
np.add(arr1, arr2)

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [8]:
arr1 + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [9]:
np.subtract(arr2, arr1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
arr2 - arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
np.multiply(arr1,arr2)

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [12]:
arr1 * arr2

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [17]:
np.divide(arr2,arr1)

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [16]:
arr2 / arr1

array([[2.        , 1.5       , 1.33333333],
       [1.25      , 1.2       , 1.16666667],
       [1.14285714, 1.125     , 1.11111111]])

In [ ]:
np.dot(arr1,arr2)       #each row of one matrix multiply with column of another matrix

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [ ]:
arr1 @ arr2             #dot product

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [22]:
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]))

In [26]:
np.max(arr2)

10

In [ ]:
np.max(arr2, axis=1)            #axis=1 : column

array([ 4,  7, 10])

In [ ]:
np.argmax(arr2)         #return index of max element

8

In [34]:
np.min(arr2)

2

In [35]:
np.min(arr2, axis=1)

array([2, 5, 8])

In [ ]:
np.argmin(arr2)          #return index of min element

0

In [ ]:
np.sum(arr2)            #sum of all elements

54

In [39]:
np.mean(arr2)

6.0

In [41]:
np.median(arr2)

6.0

If there is bell curve in graph then the mean and median value are same.

text data is also known as categorical value

In [43]:
np.std(arr2)        #standaed deviation : maximum value kaha tak yenege

2.581988897471611

In [44]:
np.log10(arr2)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        ]])