In [1]:
import numpy as np

In [ ]:
arr1 = np.random.randint(1, 100, 10)            #give random integer between 1 to 100
arr1

array([52, 43, 59, 19, 93, 16, 41, 33, 86, 73])

In [7]:
arr2 = np.random.randint(30, 100, (20, 6))              #range 30 to 100 --> 20 row and 6 column
arr2

array([[34, 69, 94, 55, 62, 80],
       [31, 58, 33, 66, 41, 53],
       [48, 33, 46, 91, 58, 67],
       [59, 49, 31, 37, 42, 48],
       [47, 47, 97, 60, 98, 41],
       [70, 97, 48, 40, 94, 74],
       [66, 61, 30, 77, 60, 36],
       [36, 86, 98, 41, 73, 54],
       [30, 68, 61, 51, 47, 59],
       [46, 51, 70, 94, 34, 40],
       [88, 71, 42, 39, 94, 48],
       [77, 61, 96, 85, 55, 73],
       [77, 98, 50, 34, 94, 69],
       [86, 92, 33, 48, 36, 69],
       [65, 57, 93, 98, 81, 36],
       [44, 70, 74, 36, 70, 67],
       [70, 62, 49, 88, 98, 66],
       [85, 72, 97, 76, 52, 51],
       [31, 68, 50, 45, 64, 57],
       [63, 83, 73, 93, 81, 64]])

In [ ]:
np.random.random(5)         #only want random number (it gives in float value)

array([0.62841325, 0.54559314, 0.71374825, 0.9451553 , 0.17232471])

In [16]:
np.random.randn(10)

array([-0.331424  , -0.08943331,  0.55889814,  0.9826442 ,  0.91772854,
        0.90106081,  1.47671188,  0.33400175, -0.0534321 ,  2.09300907])

In [ ]:
np.random.seed(40)          #used to split data into training and testing
                        #without seed it changes values at every run but i fu used seed() then it give contant value
arr1 = np.random.randint(1,100,10)
arr1

# seed() : random values with fixed

array([71, 92,  8, 38, 57, 51, 66, 13, 72, 20])

In [22]:
arr1 = np.random.randint(1,100,10)
arr1

array([74,  9, 53, 31, 80, 15, 93, 59, 75, 23])

In [ ]:
np.random.permutation(arr1)     #change the sequence of arr1 (shuffle the array)

array([92, 38,  8, 71, 51, 20, 13, 66, 57, 72])

In [ ]:
np.random.rand(5)       # rand() - give values in between 0 to 1

array([0.9514401 , 0.8634023 , 0.81362622, 0.42397361, 0.65381634])