In [11]:
import numpy as np

In [12]:
arr1 = np.random.randint(10, 20, (3,3))
arr1

array([[10, 19, 10],
       [18, 16, 16],
       [15, 16, 11]])

In [13]:
arr2 = np.random.randint(20, 30,(3,4))
arr2

array([[29, 24, 27, 22],
       [20, 23, 24, 21],
       [28, 25, 27, 24]])

In [14]:
np.concatenate((arr1, arr2), axis=1)

array([[10, 19, 10, 29, 24, 27, 22],
       [18, 16, 16, 20, 23, 24, 21],
       [15, 16, 11, 28, 25, 27, 24]])

In [26]:
arr3 = np.random.randint(30, 40, (3,4))
arr3

array([[39, 35, 30, 30],
       [34, 37, 33, 35],
       [35, 36, 32, 32]])

In [27]:
arr1, arr2, arr3

(array([[10, 19, 10],
        [18, 16, 16],
        [15, 16, 11]]),
 array([[29, 24, 27, 22],
        [20, 23, 24, 21],
        [28, 25, 27, 24]]),
 array([[39, 35, 30, 30],
        [34, 37, 33, 35],
        [35, 36, 32, 32]]))

In [28]:
np.hstack((arr1, arr3))

array([[10, 19, 10, 39, 35, 30, 30],
       [18, 16, 16, 34, 37, 33, 35],
       [15, 16, 11, 35, 36, 32, 32]])

In [30]:
np.vstack((arr2, arr3))             #for this number of columns must be same

array([[29, 24, 27, 22],
       [20, 23, 24, 21],
       [28, 25, 27, 24],
       [39, 35, 30, 30],
       [34, 37, 33, 35],
       [35, 36, 32, 32]])

In [33]:
np.split(arr2, 3)

[array([[29, 24, 27, 22]]),
 array([[20, 23, 24, 21]]),
 array([[28, 25, 27, 24]])]

In [37]:
np.split(arr3, 2, axis=1)

[array([[39, 35],
        [34, 37],
        [35, 36]]),
 array([[30, 30],
        [33, 35],
        [32, 32]])]