In [1]:
import numpy as np

In [2]:
np.sin(np.radians(30))                  #sin 30 : 1/2 = 0.5

0.49999999999999994

In [3]:
np.sin(np.radians(90))

1.0

In [4]:
np.cos(np.radians(90))

6.123233995736766e-17

In [5]:
np.tan(np.radians(90))

1.633123935319537e+16

In [7]:
arr1 = np.random.randint(35, 100, 100)
arr1

array([69, 77, 85, 88, 86, 88, 94, 45, 60, 78, 66, 72, 93, 68, 43, 65, 84,
       95, 73, 37, 57, 41, 60, 37, 60, 51, 35, 59, 91, 68, 37, 95, 43, 70,
       71, 65, 71, 91, 61, 65, 67, 91, 61, 60, 87, 87, 48, 69, 40, 89, 75,
       76, 87, 83, 80, 55, 36, 82, 79, 95, 97, 47, 78, 63, 35, 50, 47, 46,
       81, 58, 70, 61, 77, 96, 80, 52, 53, 76, 35, 86, 81, 86, 61, 85, 94,
       91, 89, 86, 61, 54, 38, 66, 73, 93, 72, 64, 86, 75, 76, 35])

In [ ]:
np.where(arr1 > 50, True, False)            # where(condition) if arr1 values is greater than 50 then True or else False

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [ ]:
np.where(arr1> 50)          # if condition is True then it gives its indexes

(array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18,
        20, 22, 24, 25, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 62,
        63, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98], dtype=int64),)